spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: awesomeMongo

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG